title: Ian and Ellie's Pub Reviews
description: A definitive guide to Sussex establishments and beyond.
baseurl: "/pub-reviews"
url: ""

# Use the built-in theme instead of the remote one
theme: minima

# Plugins that help GitHub Pages work better
plugins:
  - jekyll-feed
  - jekyll-seo-tag
